version: '3.8'

services:
  # Servizio Middleware: RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: factory_middleware
    hostname: rabbitmq-server
    ports:
      - "5672:5672"     # Porta AMQP (Python <-> RabbitMQ)
      - "15672:15672"   # Dashboard Web di gestione
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    restart: always
    networks:
      - industrial_net

  # Servizio Consumer (opzionale) se vuoi farlo girare via Docker
  consumer:
    build: .
    command: python backend_consumer.py
    depends_on:
      - rabbitmq
    networks:
      - industrial_net

networks:
  industrial_net:
    driver: bridge
